### ISSUE TITLE
Not able to scroll the page when the Keyboard is invoked

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe-authenticator-mobile#60]
We are not able to scroll the page to access Login button, when the keyboard is invoked

STR:
1. Open authenticator, the login page will be shown
2. click the secret or password text fields, so it is focused and the keyboard is invoked. 
3. try to scroll the page to access the Login button or Need Help link.

it will be useful for small screen mobiles to access the text field to enter the password

**Comment by ashwinkumar6** [comment]
When the keyboard is displayed on the screen, enable scroll for the page on Android and iOS. This is to be done on pages `CreateAcctPage` and `LoginPage`

A solution would be to add controls inside a `ScrollView` and on android, resize the `SoftInput` window using the following command
`Xamarin.Forms.Application.Current.On<Xamarin.Forms.PlatformConfiguration.Android>().UseWindowSoftInputModeAdjust(WindowSoftInputModeAdjust.Resize)`

**Comment by ashwinkumar6** [comment]
On Android, we do not require a custom control here, since the default the default behavior of `ScrollView`is that only if the contents exceed the view, the scroll is enabled. But however, on iOS scroll is enabled even if the contents don't exceed the view.

A solution to this would be to create a CustomScrollView, with a `IsScrollEnabled` custom property, such that initially the scrollView for the page is disabled and using the `Entry`'s `Focused` and `Unfocused` events we can enable/disable the scroll
