### ISSUE TITLE
Getting started tutorial page is not appearing again when you close authenticator before reading it completely

### ISSUE THREAD

**Issue by safesurfer** [maidsafe/safe-authenticator-mobile#63]
Initial loading of authenticator shows the tutorial to educate the first time user. But if you close it, before reading the tutorial completely, there is no way to see that tutorial again.

STR:
1. Open authenticator for the first time, it shows the tutorial screen.
2. Close authenticator from recent applications menu.
3. Open it again, it will show the Login page.

There is no way to see the tutorial again, if the user wants to.

**Comment by ashwinkumar6** [comment]
Currently, the tutorial page is displayed only when the app is opened for the first time. Tutorial page is to be displayed again when the user reopens the app unless he skips the tutorial by clicking Skip or he completes the tutorial by clicking Login/ Create Account button.

A quick fix would be to store the `IsFirstLaunch` property when skip, Login/ Create Account button is clicked on the CreateAcctPage rather than performing it on the `NewStartupPage` on `App.xaml.cs`

**Comment by safesurfer** [comment]
QA verified
